### ISSUE TITLE
Get appveyor working for ALL 3 windows instances

### ISSUE THREAD

**Issue by toddr** [toddr/IPC-Run#123]
Strawberry
ActiveState
cygwin

**Comment by mohawk2** [comment]
cf PDL's https://github.com/PDLPorters/pdl/blob/master/appveyor.yml which works on Strawberry.

**Comment by toddr** [comment]
The other thing here is that I'm pretty sure SP is broken due to #29

**Comment by mohawk2** [comment]
The latest released IPCR passes on my SP 5.26.2.

**Comment by toddr** [comment]
I think the windows version is the issue. what version of windows are you?

**Comment by mohawk2** [comment]
I should have said! Win 7.

**Comment by toddr** [comment]
Appveyor seems to be working on cygwin and SP. Closing for now.
