### ISSUE TITLE
How do you get PID of child?

### ISSUE THREAD

**Issue by uldics** [toddr/IPC-Run#132]
I have a Perl script using your IPC::Run and start, pump, finish mode to call an external binary, compiled, unchangeable program. I need to get the programs PID.
In the Perl script launching the external binary, I only get own PID from $$. In Bash it would be $!, Perl just gives me "Illegal seek".
How do I get the childs PID?

**Comment by diegok** [comment]
You can access `$harness->_running_kids` which returns a list of hashes where you can access PID property. It's not documented, and not recommended to access a private method, but there is no other way :-1: 

We use something like this:

```perl
my $harness = IPC::Run::harness(...);
$harness->start;
my ($child) = $harness->_running_kids;
my $child_pid = $child->{PID};
```
