### ISSUE TITLE
[feature request] kill all subtree after timeout

### ISSUE THREAD

**Issue by avkhozov** [toddr/IPC-Run#17]
If a subprocess create a new child with new session, then this child not killed after timeout. It would be nice, if we can pass option to `run` (for example `kill_subtree => 1`) and `kill_kill` would use negative pid for kill all subtree: `kill $signal, -$_->{PID}`

``` perl
$ cat 1.pl
#!/usr/bin/perl -l

use IPC::Run qw/run timeout/;

warn "$$";
eval { run ["./1.sh"], \undef, \$a, \$b, timeout(5) };
warn "$a => $b";
warn $@ if $@;
$ cat 1.sh
#!/bin/bash

echo $$
setsid /bin/ping 8.8.8.8 &>/dev/null
$ 
```

If run `perl 1.pl` and show process while perl run and after exit, then we can see, than `ping` was not killed.

``` bash
$ perl 1.pl
10796 at 1.pl line 5.
10797
 =>  at 1.pl line 7.
IPC::Run: timeout on timer #1 at /home/and/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/IPC/Run.pm line 2961.
$ 

$ # perl in progress
$ pstree -apl 10796
perl,10796 1.pl
  └─1.sh,10797 ./1.sh
      └─ping,10798 8.8.8.8
$ # perl fihished
$ pstree -apl 10797
$ pstree -apl 10798
ping,10798 8.8.8.8
$ 
```

**Comment by avkhozov** [comment]
Hello there! Is it reasonable to expect some feedback about this issue?

**Comment by toddr** [comment]
Do you have a proposed patch for this?
