### ISSUE TITLE
Out of date repo description

### ISSUE THREAD

**Issue by jwilk** [toddr/IPC-Run#22]
The GitHub repository description reads:
> Clone of http://svn.ali.as/cpan/trunk/IPC-Run

But the GitHub repo has been the primary one since cd12715b9185803b6d507a666d0d5bb67b4a5aae, and http://svn.ali.as/cpan/trunk/IPC-Run/ hasn't been updated for years.

**Comment by toddr** [comment]
When I moved to git I was actively using the above SVN repo. It is what I forked from when I started using git. What do you think should be changed?
