### ISSUE TITLE
Pumping UTF-8 data mangles it [rt.cpan.org #58853]

### ISSUE THREAD

**Issue by toddr** [toddr/IPC-Run#87]
Migrated from [rt.cpan.org#58853](https://rt.cpan.org/Ticket/Display.html?id=58853) (status was 'open')

Requestors:
* tino.didriksen+ipcrun@gmail.com

Attachments:
* [ipc-run-fail.pl](https://rt.cpan.org/Ticket/Attachment/797083/413255/ipc-run-fail.pl)

unknown user
```
Attached is a self-contained test script that shows how pump does not
manage to send all UTF-8 data to the child, despite the environment vars
PERL_UNICODE=SDA LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 being set.

I tried looking through IPC/Run.pm and by adding "use bytes;" to
_write() that part will at least send the data correctly.

However, I couldn't get it to read back the output from the child as
UTF-8; it just reads the raw bytes interpreted as ISO-8859-1, and
forcing all _read() strings to UTF-8 seemed like a really bad idea...

Somewhere there must be a place where it does not respect the global
binmode, since PERL_UNICODE=SDA should force all I/O to UTF-8 semantics.
```

From ddumont@cpan.org on 2011-02-04 08:40:44:
```
On Sat Jun 26 14:22:07 2010,
https://www.google.com/accounts/o8/id?id=AItOawmVIxZvJRV891D4v94gdb3PG8qiqj4xy9M
wrote:
> PERL_UNICODE=SDA LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 being set.
> 

I think IPC::Run should test the locale. If UTF-8 is used, call
binmode(":utf8") on all pipe filehandles *before* using them.

See perldoc -f binmode for more details.

```

**Comment by martinvonwittich** [comment]
`IPC::Run` generally doesn't seem to work properly when used in a script with `-CSDAL`:

    #!/usr/bin/perl -CSDAL
    use warnings;
    use strict;
    use IPC::Run;
    
    my $out;
    IPC::Run::run ['bash', '-c', q{echo $'\u00E4\u00F6\u00FC'}],
        \undef, \$out, \*STDERR;
    print $out;

This should print "äöü", but instead it prints "Ã¤Ã¶Ã¼". To work around this issue, one needs to manually decode the output with `utf8::decode $out` :(

**Comment by toddr** [comment]
It seems like we'd need to find a way to specify that opens need to happen with a layer in order to get this to work. I'm going to treat this as a feature request for now since it's always been this way. Patches are welcome if someone has ideas.

**Comment by toddr** [comment]
The example script inline 

```perl
#!/usr/bin/perl
# Runtime environment: export LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PERL_UNICODE=SDA
BEGIN { $| = 1; }
use utf8;
use strict;
use warnings;

if (! defined $ENV{IPC_SUB_PROCESS}) {
    $ENV{IPC_SUB_PROCESS} = 1;
    use IPC::Run qw( start pump finish timeout binary );
    my $in;
    my $out;
    my @cmd = (__FILE__);
    my $h = start \@cmd, \$in, \$out, timeout(2);
    
    my @lines = ("abc", "料理教室", "æøå");

    foreach my $line (@lines) {
        print "Handler input: $line\n";
        $in = $line;
        $in .= "\n";
        pump $h until $out =~ /.+/s;
        print "Handler output: $out\n";
        $out = '';
    }
}
else {
    while (my $line = <STDIN>) {
        $line =~ s/^\s+//g;
        $line =~ s/\s+$//g;
        print STDERR "Daemon input/output: ", $line, "\n";
        print $line, "\n";
    }
}
```

**Comment by martinvonwittich** [comment]
> `bash`’s output is an octet sequence, which you’re storing in `$out`

Hm, I would've expected `IPC::Run` to auto-UTF-8-decode this when running with `-CSDAL`.

**Comment by FGasper** [comment]
> I would've expected IPC::Run to auto-UTF-8-decode this when running with -CSDAL.

FWIW I personally wouldn’t. Is there something in IPC::Run’s documentation that suggests it would work that way?

**Comment by martinvonwittich** [comment]
> FWIW I personally wouldn’t. Is there something in IPC::Run’s documentation that suggests it would work that way?

No, as far as I can tell, the `IPC::Run` docs don't mention Unicode or UTF-8 at all. But seen from the other way around - `-CSDA(L)` enables auto-UTF-8-decode/encode for `@ARGV`, STDIN/STDOUT/STDERR, and I kinda interpreted it as "toggle this single switch, and Perl will consider the whole "outside" as UTF-8, so no more manually decoding/encoding everything". And this does e.g. include `qx`:

```
#!/usr/bin/perl -CSDAL
use warnings;
use strict;

my $echo = q{echo $'\u00E4\u00F6\u00FC'};
print qx(bash -c "$echo");
```

```
host ~ # ./test.pl
äöü
```

But obviously not `IPC::Run`, which I use mainly as a more powerful `qx`/`system` replacement. Contrary to what I said in 2017 I probably wouldn't argue any longer that `IPC::Run`s behaviour is "wrong", but I did find this very surprising back when I didn't know about it.

**Comment by FGasper** [comment]
Yeah, that’s why I avoid `-CS` and such; it’s too hard to track where the “auto-decode/encode” magic happens and where it doesn’t. At least “out of the box” Perl is consistent.

The fact that Perl doesn’t distinguish octet/byte strings from text/character strings continually confuses even Perl veterans. This kind of thing is much rarer in Python, JS, Rust, and other languages where text strings and octet strings are different types.

I’m going to close this, then, since there doesn’t actually seem to be a problem to fix.
