### ISSUE TITLE
perldoc and README.md should tell users to submit bugs to github, not rt.cpan.org

### ISSUE THREAD

**Issue by pmorch** [toddr/IPC-Run#96]
The perldoc (and the github README.md) have this:

```
SUPPORT
    Bugs should always be submitted via the CPAN bug tracker
    <http://rt.cpan.org/NoAuth/ReportBug.html?Queue=IPC-Run>
    For other issues, contact the maintainer (the first listed author)
```

So I submitted a bug [to rt.cpan.org](https://rt.cpan.org/Public/Bug/Display.html?id=121383) that then got moved to github as #66. The original rt.cpan.org bug got closed.

If github is actually preferred for bugs - and I totally relate - then I suggest changing the perldoc and README.md accordingly.

**Comment by toddr** [comment]
Baby steps!

**Comment by toddr** [comment]
Will be updated in 0.97
